# Generated by Django 5.0.1 on 2024-05-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gornyak', '0003_location_sport_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('registration', 'Регистрация'), ('completed', 'Завершено')], default='registration', max_length=50),
        ),
    ]
