# Generated by Django 5.0.1 on 2024-05-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gornyak', '0005_event_event_type_event_max_team_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_team_size',
        ),
        migrations.RemoveField(
            model_name='event',
            name='min_team_size',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
