# Generated by Django 5.0.1 on 2024-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gornyak', '0006_remove_event_event_type_remove_event_max_team_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=10),
        ),
    ]
