# Generated by Django 5.0.1 on 2024-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gornyak', '0009_alter_eventregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
