# Generated by Django 5.0.1 on 2024-06-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gornyak', '0010_alter_event_end_datetime_alter_event_start_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['status', 'start_datetime'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('individual', 'Индивидуальное'), ('team', 'Командное')], default='individual', max_length=10),
        ),
    ]
