# Generated by Django 5.0.1 on 2024-06-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gornyak', '0011_alter_event_options_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
