# Generated by Django 5.0.1 on 2024-06-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gornyak', '0013_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
