# Generated by Django 5.0.1 on 2024-06-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gornyak', '0014_delete_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['status', 'start_datetime'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
